### ISSUE TITLE
Need to be able to config OCI_CONFIG_FILE

### ISSUE THREAD

**Issue by gsriganesha** [micronaut-projects/micronaut-oracle-cloud#136]
mn is looking for OCI config file under USER_HOME/.oci/config. This need to be configurable; support for OCI_CONFIG_FILE env var.

Error: [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.oraclecloud.core.TenancyIdProvider] could not be loaded: Error instantiating bean of type [io.micronaut.oraclecloud.core.TenancyIdProvider]: Invalid Oracle Cloud Configuration. If you are running locally ensure the CLI is configured by running: oci setup config
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.oraclecloud.core.TenancyIdProvider] could not be loaded: Error instantiating bean of type [io.micronaut.oraclecloud.core.TenancyIdProvider]: Invalid Oracle Cloud Configuration. If you are running locally ensure the CLI is configured by running: oci setup config

**Comment by pgressa** [comment]
Hi @gsriganesha , based on the https://github.com/oracle/oci-java-sdk/blob/master/bmc-common/src/main/java/com/oracle/bmc/ConfigFileReader.java#L73 the OCI SDK supports this env var. However based on the code, the `~/.oci/config` takes precedence over the env variable. To not change the SDK behaviour in terms of different order of config files, I have added in #137 ability to specify the path explicitly as micronaut property. Once merged, you should be able to do: 
```
oci:
  config:
    path: ${OCI_CONFIG_FILE}
```
