### ISSUE TITLE
ATP modules missing from BOM

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-oracle-cloud#228]
The ATP modules are not included in the `micronaut-oraclecloud-bom` for some reason

**Comment by graemerocher** [comment]
actually it is worse, 1.4.0 is not published in maven central at all

**Comment by pgressa** [comment]
Needed to release the 1.4.1 since the bom was already released.

https://s01.oss.sonatype.org/content/repositories/releases/io/micronaut/oraclecloud/micronaut-oraclecloud-bom/1.4.1/micronaut-oraclecloud-bom-1.4.1.pom
