### ISSUE TITLE
Function is failing to download database wallet

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-oracle-cloud#306]
### Issue description

Probably caused by upgrade of ociVersion to 2.x along with upgrade of module to support Micronaut 3.

https://github.com/oracle/oci-java-sdk/compare/v1.37.2...v2.0.0

![Screenshot 2021-11-30 at 15 24 34](https://user-images.githubusercontent.com/1838702/144065011-c2fe340c-4abe-4350-a447-0e1b9636ce09.png)

**Comment by burtbeckwith** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/307 / https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/319
