### ISSUE TITLE
BOM contains unresolvable dependencies

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-oracle-cloud#359]
### Issue description

BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-oraclecloud-sdk-processor:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-oraclecloud-atp-hikari-test:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-oraclecloud-atp-ucp-test:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-example-http-function-java:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-example-function-groovy:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-example-http-function-kotlin:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-example-groovy:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-example-function-java:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-example-java:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-example-http-function-groovy:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-example-function-kotlin:2.1.1
BOM io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.oraclecloud:micronaut-oraclecloud-bom:2.1.1) declares a non-resolvable dependency: io.micronaut.oraclecloud:micronaut-example-kotlin:2.1.1

**Comment by alvarosanchez** [comment]
No longer valid
