### ISSUE TITLE
Confusion in ConfigFileAuthenticationDetailsProvider bean requirements

### ISSUE THREAD

**Issue by dmeibusch** [micronaut-projects/micronaut-oracle-cloud#404]
I believe there is a contradiction in the bean requirements for using `ConfigFileAuthenticationDetailsProvider` with a config file in a location other than `~/.oci/config`.

See https://github.com/micronaut-projects/micronaut-oracle-cloud/blob/51a117119e20e55db1cae5584e836a623aaba051/oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudCoreFactory.java#L91

This bean currently requires 
```
@Requires(condition = OracleCloudConfigCondition.class)
```
The `OracleCloudConfigCondition` requires either `oci.config` to be directly set to the path of an existing config file, or `~/.oci/config` to exist.

However `OracleCloudCoreFactory.configFileAuthenticationDetailsProvider` is configured based on `oci.config.path`.

It gets confusing as this often works, you have an existing `~/.oci/config` (which you don't use) and you've configured `oci.config.path`. The latter will work and be used, but only if the `~/.oci/config` exists. Works for development, then fails in a container image.

**Comment by dmeibusch** [comment]
Cool, issue number assigned is `404` - config file not found. :-)

**Comment by graemerocher** [comment]
@n0tl3ss please look at this
