### ISSUE TITLE
Remove accessing internal GraalVM API classes

### ISSUE THREAD

**Issue by dradosevic** [micronaut-projects/micronaut-oracle-cloud#432]
### Expected Behavior

Apps using micronaut-oracle-cloud can be built into GraalVM native images.

### Actual Behaviour

The classes from `com.oracle.svm` packages in graal sdk are not accessible in the more recent versions of GraalVM (e.g. 22.2), which is causing errors during native image build (see for example https://github.com/oracle-quickstart/oci-micronaut/actions/runs/3360675120/jobs/5570386160 ). The classes from these packages can be replaced by classes from `org.graalvm.nativeimage ` which is public (https://github.com/oracle/graal/pull/4783#issuecomment-1208055959) . I found classes 'com.oracle.svm.core.annotate.AutomaticFeature' and 'com.oracle.svm.core.jni.JNIRuntimeAccess' being used in micronaut oracle cloud.

### Steps To Reproduce

1. run native build for the example application : `./gradlew nativeCompile` - the build cannot complete because of `java.lang.IllegalAccessError`

### Environment Information

JDK Version: 11
GraalVM Version : 22.2

### Example Application

https://github.com/dradosevic/graalvmJniPackageAccessDemo

### Version

3.7.2

**Comment by graemerocher** [comment]
Needs to be changed to use `org.graalvm.nativeimage.hosted.RuntimeJNIAccess` instead

**Comment by graemerocher** [comment]
This is present since GraalVM 22.3

**Comment by yawkat** [comment]
odd,  #436 runs fine without this change. is it just that oraclecloud-function doesnt have native-image test coverage?

**Comment by graemerocher** [comment]
looks that way

**Comment by yawkat** [comment]
ive pushed this change to #436, however i'm still having some trouble setting up nativeTest to work with functions.
