### ISSUE TITLE
Upgrade to Oracle Cloud SDK v3

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-oracle-cloud#434]
### Feature description

We should upgrade to Oracle Cloud SDK v3 and provide a Netty HTTP transport

**Comment by graemerocher** [comment]
@yawkat please prioritize this. We need to do this for both 3.x and 4.x

For 3.x we cannot upgrade to a new major version, but we can provide a module that is compatible

**Comment by yawkat** [comment]
yea i'm working on this atm
