### ISSUE TITLE
Support for OKE workload identity

### ISSUE THREAD

**Issue by dmeibusch** [micronaut-projects/micronaut-oracle-cloud#630]
### Feature description

All in the title, support k8s workload identities introduced in OKE.
https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contenggrantingworkloadaccesstoresources.htm

Requires OCI SDK 2.54+

We did a brief experiment following the existing Instance Principal auth provider pattern - looks low cost.

**Comment by alvarosanchez** [comment]
Fixed by #686
