### ISSUE TITLE
Add support for `OkeWorkloadIdentityAuthenticationDetailsProvider`

### ISSUE THREAD

**Issue by yawkat** [micronaut-projects/micronaut-oracle-cloud#683]
### Issue description

`OkeWorkloadIdentityAuthenticationDetailsProvider` uses `StandardClientProperties.HOSTNAME_VERIFIER` and `StandardClientProperties.SSL_CONTEXT` which are not supported by the netty client. Likely `OkeWorkloadIdentityAuthenticationDetailsProvider` will have to be replaced by code that uses micronaut http client configuration properties to configure tls instead.

**Comment by alvarosanchez** [comment]
Isn't this the same as #630?

**Comment by yawkat** [comment]
yes
