### ISSUE TITLE
Function Server TCK: RequestFilterTest failing

### ISSUE THREAD

**Issue by andriy-dmytruk** [micronaut-projects/micronaut-oracle-cloud#926]
### Issue description

The Server TCK was added in this PR: https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/920.

Currently `RequestFilterTest` is failing. 

The reason is that the `BaseFilterProcessor` expects an instance of `ServerHttpRequest` that can provide the body with `ByteBody byteBody()` method: https://github.com/micronaut-projects/micronaut-core/blob/39818ada8f3cabbe17ee4d61e19e13e4e0d1fef4/http/src/main/java/io/micronaut/http/filter/BaseFilterProcessor.java#L93-L109. This is not possible in this case, because InputEvent expects body input stream to be consumed immediately instead of giving it for further use.

In the https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/923 PR I added method `consumeBody(Function<InputStream, T>)` but it won't work in this case.

cc @yawkat

**Comment by yawkat** [comment]
should be fixed by my change to #923
